sonar.projectKey=custom-tetris
sonar.projectName=Custom Tetris
sonar.sources=src
sonar.host.url=http://localhost:9000
# Pega aquí el código largo que copiaste antes:
sonar.login=sqp_f890aa9c8c2a94bdcfb5da0c001e1d93ed8e0f96
# Esto ayuda a que entienda que es TypeScript/React:
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8