import type { Theme } from './types';

export const THEMES: Theme[] = [
  {
    id: 'classic',
    label: 'Classic',
    blockStyle: 'classic',
    ghostAlpha: 0.22,
    cssVars: {
      '--bg':          '#0d0d1a',
      '--surface':     '#16162a',
      '--border':      '#7f5af0',
      '--accent':      '#7f5af0',
      '--accent-2':    '#cb8cff',
      '--text':        '#e0e0e0',
      '--text-muted':  '#888',
      '--canvas-bg':   '#0a0a14',
      '--canvas-grid': '#1a1a2e',
      '--glow':        '0 0 20px #7f5af0',
      '--font-family': "'Segoe UI', sans-serif",
      '--font-heading':"'Segoe UI', sans-serif",
    },
    tetrominoColors: {
      I: '#00cfcf', O: '#f0d000', T: '#a000f0',
      S: '#00c000', Z: '#c00000', J: '#0050f0', L: '#f0a000',
    },
  },
  {
    id: 'retro',
    label: 'Retro',
    blockStyle: 'retro',
    ghostAlpha: 0.25,
    cssVars: {
      '--bg':          '#000000',
      '--surface':     '#0a0a0a',
      '--border':      '#00ff41',
      '--accent':      '#00ff41',
      '--accent-2':    '#39ff14',
      '--text':        '#00ff41',
      '--text-muted':  '#005c16',
      '--canvas-bg':   '#000000',
      '--canvas-grid': '#001a07',
      '--glow':        '0 0 12px #00ff41',
      '--font-family': "'Courier New', monospace",
      '--font-heading':"'Courier New', monospace",
    },
    tetrominoColors: {
      I: '#00ff41', O: '#39ff14', T: '#00cc33',
      S: '#00ff99', Z: '#007a1f', J: '#009933', L: '#00e676',
    },
  },
  {
    id: 'neon',
    label: 'Neon',
    blockStyle: 'glow',
    ghostAlpha: 0.2,
    cssVars: {
      '--bg':          '#000000',
      '--surface':     '#05051a',
      '--border':      '#ff00ff',
      '--accent':      '#ff00ff',
      '--accent-2':    '#00ffff',
      '--text':        '#ffffff',
      '--text-muted':  '#888',
      '--canvas-bg':   '#000000',
      '--canvas-grid': '#0a0018',
      '--glow':        '0 0 24px #ff00ff, 0 0 48px #ff00ff55',
      '--font-family': "'Segoe UI', sans-serif",
      '--font-heading':"'Segoe UI', sans-serif",
    },
    tetrominoColors: {
      I: '#00ffff', O: '#ffff00', T: '#ff00ff',
      S: '#00ff88', Z: '#ff2244', J: '#3366ff', L: '#ff8800',
    },
  },
  {
    id: 'minimal',
    label: 'Minimal',
    blockStyle: 'flat',
    ghostAlpha: 0.18,
    cssVars: {
      '--bg':          '#f0f0f0',
      '--surface':     '#ffffff',
      '--border':      '#cccccc',
      '--accent':      '#333333',
      '--accent-2':    '#666666',
      '--text':        '#111111',
      '--text-muted':  '#777777',
      '--canvas-bg':   '#ffffff',
      '--canvas-grid': '#e8e8e8',
      '--glow':        'none',
      '--font-family': "'Helvetica Neue', Arial, sans-serif",
      '--font-heading':"'Helvetica Neue', Arial, sans-serif",
    },
    tetrominoColors: {
      I: '#aedff7', O: '#fce38a', T: '#d7aefb',
      S: '#b5efc0', Z: '#f5a9a9', J: '#a9c4f5', L: '#fddcae',
    },
  },
  {
    id: 'ocean',
    label: 'Ocean',
    blockStyle: 'gradient',
    ghostAlpha: 0.22,
    cssVars: {
      '--bg':          '#021c2e',
      '--surface':     '#052840',
      '--border':      '#00b4d8',
      '--accent':      '#00b4d8',
      '--accent-2':    '#90e0ef',
      '--text':        '#caf0f8',
      '--text-muted':  '#0077b6',
      '--canvas-bg':   '#011627',
      '--canvas-grid': '#032d4a',
      '--glow':        '0 0 18px #00b4d8',
      '--font-family': "'Segoe UI', sans-serif",
      '--font-heading':"'Segoe UI', sans-serif",
    },
    tetrominoColors: {
      I: '#00b4d8', O: '#90e0ef', T: '#0077b6',
      S: '#48cae4', Z: '#023e8a', J: '#0096c7', L: '#ade8f4',
    },
  },
  {
    id: 'sunset',
    label: 'Sunset',
    blockStyle: 'gradient',
    ghostAlpha: 0.22,
    cssVars: {
      '--bg':          '#1a0a00',
      '--surface':     '#2b1100',
      '--border':      '#ff6b35',
      '--accent':      '#ff6b35',
      '--accent-2':    '#ffb347',
      '--text':        '#ffe5cc',
      '--text-muted':  '#a05020',
      '--canvas-bg':   '#12070a',
      '--canvas-grid': '#2a0e0e',
      '--glow':        '0 0 18px #ff6b35',
      '--font-family': "'Segoe UI', sans-serif",
      '--font-heading':"'Segoe UI', sans-serif",
    },
    tetrominoColors: {
      I: '#ff6b35', O: '#ffb347', T: '#ff4785',
      S: '#ffd166', Z: '#c1121f', J: '#e07a5f', L: '#f4a261',
    },
  },
];

export const DEFAULT_THEME_ID = 'classic';
